### ISSUE TITLE
Lots of warning

### ISSUE THREAD

**Issue by nickelcheng** [bruce3557/NTHUOJ_web#98]
When I'm loading contest page, it appears lots of "WARNING: User username  does not exsit!"
@Changron can you fix it?

**Comment by Changron** [comment]
i think it is because when i call "has contest ownership"
![2015-04-01 08 41 35](https://cloud.githubusercontent.com/assets/9431996/6932387/31630c8c-d84b-11e4-8ef8-a3475e75f9f6.png)
it calls "user_is_valid"
![2015-04-01 08 41 19](https://cloud.githubusercontent.com/assets/9431996/6932392/3725fa62-d84b-11e4-98fa-3bc2ac559a73.png)
if not login, it will pop up lots of warning

**Comment by henryyang42** [comment]
This is fixed in #80
